dicci1={
persona1={'nombre':'Alejandro','sexo':'M','gafas':'yes','barba':'no','pendientes':'no','color_pelo':'marrón','gorra':'yes'}
persona2={'nombre':'Sara','sexo':'F','gafas':'no','barba':'no','pendientes':'yes','color_pelo':'negra','gorra':'no'}
persona3={'nombre':'Pedro','sexo':'M','gafas':'no','barba':'yes','pendientes':'yes','color_pelo':'rubio','gorra':'yes'}
persona4={'nombre':'Carla','sexo':'F','gafas':'yes','barba':'no','pendientes':'no','color_pelo':'lila','gorra':'no'}
persona5={'nombre':'Lewis','sexo':'M','gafas':'no','barba':'yes','pendientes':'yes','color_pelo':'negro','gorra':'yes'}
persona6={'nombre':'Luis','pelo_largo':'no','pelo_corto':'Yes','bigote':'No','calvo':'No'}
persona7={'nombre':'Maricarmen','sexo':'F','pelo_largo':'es','pelo_corto':'No','bigote':'No','calvo':'No'}
persona8={'nombre':'Alex','pelo_largo':'no','pelo_corto':'yes','bigote':'Yes','calvo':'No'}
persona9={'nombre':'Alejandra','pelo_largo':'yes','pelo_corto':'No','bigote':'No','calvo':'No'}
persona10={'nombre':'Joan','pelo_largo':'yes','pelo_corto':'no','bigote':'Yes','calvo':'No'}
}
